spring:
  cloud:
    config:
      server:
        git:
          #uri: C:\work\ksr\kolkata2020labsconfig
          uri: https://github.com/prabhakarmishra/Newboot.git
          #searchPaths: ConfigData
          skipSslValidation: true
  application:
    name: cloud-config-server
server:
  port: 8888
